import sys

if __name__ != "__main__":
    sys.exit()

from PyQt5 import QtCore, QtGui, QtWidgets
from Simulation import Simulation
from Controller import Controller


# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'control_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
class Ui_MainWindow(object):

    __controller: Controller = None

    def setupUi(self, MainWindow, controller: Controller):
        
        self.__controller = controller

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(812, 634)
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(330, 390, 271, 181))
        self.graphicsView.setObjectName("graphicsView")
        # picture
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_2.setGeometry(QtCore.QRect(10, 390, 200, 181))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.graphicsView_2.setStyleSheet("background:transparent;")
        pix = QtGui.QPixmap('./crane.jpg')
        item = QtWidgets.QGraphicsPixmapItem(pix)
        item.setScale(0.35)
        scene = QtWidgets.QGraphicsScene(self.centralwidget)
        scene.addItem(item)
        self.graphicsView_2.setScene(scene)

        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(150, 300, 131, 27))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(10, 300, 131, 27))
        self.pushButton_7.setObjectName("pushButton_7")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 260, 271, 31))
        self.textBrowser.setObjectName("textBrowser")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 240, 131, 16))
        self.label_5.setObjectName("label_5")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(660, 30, 131, 31))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(660, 10, 131, 16))
        self.label_6.setObjectName("label_6")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(330, 240, 91, 16))
        self.label_10.setObjectName("label_10")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(470, 300, 131, 27))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(330, 300, 131, 27))
        self.pushButton_10.setObjectName("pushButton_10")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_4.setGeometry(QtCore.QRect(330, 260, 271, 31))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(390, 130, 71, 31))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lcdNumber_5 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_5.setGeometry(QtCore.QRect(480, 30, 131, 31))
        self.lcdNumber_5.setObjectName("lcdNumber_5")
        self.horizontalSlider_5 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_5.setGeometry(QtCore.QRect(330, 170, 271, 29))
        self.horizontalSlider_5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_5.setObjectName("horizontalSlider_5")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(480, 110, 131, 20))
        self.label_8.setObjectName("label_8")
        self.horizontalSlider_6 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_6.setGeometry(QtCore.QRect(330, 70, 271, 29))
        self.horizontalSlider_6.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_6.setObjectName("horizontalSlider_6")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(330, 30, 41, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(480, 10, 131, 20))
        self.label_9.setObjectName("label_9")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(390, 30, 71, 31))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(330, 130, 41, 31))
        self.pushButton_8.setObjectName("pushButton_8")
        self.lcdNumber_6 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_6.setGeometry(QtCore.QRect(480, 130, 131, 31))
        self.lcdNumber_6.setObjectName("lcdNumber_6")
        self.lcdNumber_7 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_7.setGeometry(QtCore.QRect(160, 30, 131, 31))
        self.lcdNumber_7.setObjectName("lcdNumber_7")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(160, 10, 131, 20))
        self.label_11.setObjectName("label_11")
        self.lcdNumber_8 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_8.setGeometry(QtCore.QRect(160, 130, 131, 31))
        self.lcdNumber_8.setObjectName("lcdNumber_8")
        self.horizontalSlider_7 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_7.setGeometry(QtCore.QRect(10, 70, 271, 29))
        self.horizontalSlider_7.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_7.setObjectName("horizontalSlider_7")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(10, 130, 41, 31))
        self.pushButton_11.setObjectName("pushButton_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(160, 110, 131, 20))
        self.label_12.setObjectName("label_12")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(10, 30, 41, 31))
        self.pushButton_12.setObjectName("pushButton_12")

        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(640, 390, 131, 27))
        self.pushButton_13.setObjectName("pushButton_13")

        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(640, 440, 131, 27))
        self.pushButton_14.setObjectName("pushButton_14")


        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(70, 130, 71, 31))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalSlider_8 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_8.setGeometry(QtCore.QRect(10, 170, 271, 29))
        self.horizontalSlider_8.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_8.setObjectName("horizontalSlider_8")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(70, 30, 71, 31))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 370, 58, 14))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(330, 370, 271, 14))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 812, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_6.setText(_translate("MainWindow", "Desligar"))
        self.pushButton_7.setText(_translate("MainWindow", "Ligar"))
        self.label_5.setText(_translate("MainWindow", "Status do Guindaste"))
        self.label_6.setText(_translate("MainWindow", "Sensor de Distância"))
        self.label_10.setText(_translate("MainWindow", "Status do Ímã"))
        self.pushButton_9.setText(_translate("MainWindow", "Desligar"))
        self.pushButton_10.setText(_translate("MainWindow", "Ligar"))
        self.label_8.setText(_translate("MainWindow", "Altura da Ferramenta"))
        self.pushButton_5.setText(_translate("MainWindow", "OK"))
        self.label_9.setText(_translate("MainWindow", "Avanço da Ferramenta"))
        self.pushButton_8.setText(_translate("MainWindow", "OK"))
        self.label_11.setText(_translate("MainWindow", "Ângulo da Ferramenta"))
        self.pushButton_11.setText(_translate("MainWindow", "OK"))
        self.label_12.setText(_translate("MainWindow", "Ângulo da Lança"))
        self.pushButton_12.setText(_translate("MainWindow", "OK"))
        self.pushButton_13.setText(_translate("MainWindow", "Câmera 1"))
        self.pushButton_14.setText(_translate("MainWindow", "Câmera 2"))
        #self.label.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "Visualização da Câmera"))

    def set_input_listeners(self) -> None:
        
        self.horizontalSlider_8.valueChanged.connect(self.__set_arm_vel)
        self.horizontalSlider_6.valueChanged.connect(self.__set_crab_vel)
        self.horizontalSlider_7.valueChanged.connect(self.__set_hoist_angular_vel)
        self.horizontalSlider_5.valueChanged.connect(self.__set_hoist_vertical_vel)
        
        self.pushButton_7.clicked.connect(self.__start_simulation)
        self.pushButton_6.clicked.connect(self.__stop_simulation)
        self.pushButton_10.clicked.connect(self.__turn_magnet_on)
        self.pushButton_9.clicked.connect(self.__turn_magnet_off)

    def __start_simulation(self) -> None:
        self.__controller.start_simulation()

    def __stop_simulation(self) -> None:
        self.__controller.stop_simulation()

    def __turn_magnet_on(self) -> None:
        self.__controller.turn_magnet_on()

    def __turn_magnet_off(self) -> None:
        self.__controller.turn_magnet_off()

    def __stop_simulation(self) -> None:
        self.__controller.stop_simulation()

    def __set_arm_vel(self, level: int) -> None:
        self.__controller.set_arm_vel(level)
        
    def __set_crab_vel(self, level: int) -> None:
        self.__controller.set_crab_vel(level)

    def __set_hoist_vertical_vel(self, level: int) -> None:
        self.__controller.set_hoist_vertical_vel(level)

    def __set_hoist_angular_vel(self, level: int) -> None:
        self.__controller.set_hoist_angular_vel(level)

simulation: Simulation = None
app: QtWidgets.QApplication = None

try:

    # Captura IP customizado (se houver)
    ip = sys.argv[1] if (len(sys.argv) > 1) else None
    if (len(sys.argv) > 1):
        ip = sys.argv[1]

    # Inicia simulacao
    simulation = Simulation()
    is_connected, client_id, conn_error = simulation.connect(ip) if ip else simulation.connect()
    if (not is_connected):
        raise ConnectionError(conn_error)

    # Iniciar controlador & tela
    app = QtWidgets.QApplication(sys.argv)
    
    window = QtWidgets.QMainWindow()
    controller = Controller(simulation)
    ui = Ui_MainWindow()
    ui.setupUi(window, controller)
    ui.set_input_listeners()
    
    window.show()
    sys.exit(app.exec_())
            
except ConnectionAbortedError as conn_error:
    print('\nFailure as trying to start simulation: ', conn_error)
    raise conn_error

except ConnectionError as conn_error:
    print('\nLost connestr()ction to simulation: ', conn_error)
    raise conn_error

except KeyboardInterrupt:
    pass

except Exception as error:
    print('\nFalha inesperada: ', error)
    raise error

finally:
    print('\n-- THE END --\n')
    if simulation:
        simulation.disconnect()
    
